version: "3.3"

services:

  nginx_dev:
    image: "registry.digitalocean.com/fernando88to/nginx_load_balancer_proxy:${TAG_NGINX}"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      #- ./certbot/www:/var/www/certbot/:ro
      #- ./certbot/conf/:/etc/nginx/ssl/:ro
      #- ./dhparam:/etc/ssl/certs
    restart: always
    networks:
      - default

#  certbot:
#    image: certbot/certbot
#    container_name: certbot
#    volumes:
#      - ./certbot/www/:/var/www/certbot/:rw
#      - ./certbot/conf/:/etc/letsencrypt/:rw
#    depends_on:
#      - nginx_dev
#    command: certonly --webroot --webroot-path /var/www/certbot/ --email fernando88to@gmail.com --agree-tos  -d applicacao.dev.br -d www.applicacao.dev.br
#    networks:
#      - default
#    tty: true

networks:
  default:
    driver: bridge
