version: "3.3"

services:

  nginx_dev:
    image: "registry.digitalocean.com/fernando88to/nginx_load_balancer_proxy:${TAG_NGINX}"
    ports:
      - "80:80"
#    volumes:
#      - certbot-etc:/etc/letsencrypt
#      - certbot-var:/var/lib/letsencrypt
    restart: unless-stopped
    networks:
      - default


#volumes:
#  certbot-etc:
#  certbot-var:

networks:
  default:
    driver: bridge
