version: "3.9"

services:

  nginx_dev:
    image: nginx:1.17.9
    ports:
      - "80:80"
#    volumes:
#      - ./nginx/default.dev.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - default






networks:
  default:
    driver: bridge
