version: "3.3"

services:

  nginx_dev:
    image: registry.digitalocean.com/fernando88to/nginx_load_balancer_proxy${TAG}
    ports:
      - "80:80"
#    volumes:
#      - ./nginx/default.dev.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - default


networks:
  default:
    driver: bridge
